import { WORKFLOW_PHASE_LABELS } from './workflowPhases'

/** Comportamientos de paso (alineado con backend). */
export const WORKFLOW_BEHAVIOR_OPTIONS = [
  { value: 'AWAITING_FILES', label: WORKFLOW_PHASE_LABELS.AWAITING_FILES },
  { value: 'ARCHITECTURE_REVIEW', label: WORKFLOW_PHASE_LABELS.ARCHITECTURE_REVIEW },
  { value: 'SPECIFICATIONS', label: WORKFLOW_PHASE_LABELS.SPECIFICATIONS },
  { value: 'BUDGETING_PIPELINE', label: WORKFLOW_PHASE_LABELS.BUDGETING_PIPELINE },
  { value: 'MANAGEMENT_APPROVAL', label: WORKFLOW_PHASE_LABELS.MANAGEMENT_APPROVAL },
  { value: 'BUDGET_APPROVED', label: WORKFLOW_PHASE_LABELS.BUDGET_APPROVED },
  { value: 'COMPLETE', label: WORKFLOW_PHASE_LABELS.COMPLETE },
  { value: 'CUSTOM_AUTOMATION', label: 'Automatización / sin validación ISO' },
] as const
